### ISSUE TITLE
Empty multiline raises ValueError

### ISSUE THREAD

**Issue by offa** [priv-kweihmann/oelint-adv#225]
An empty multiline value crashes the analysis.

```
Traceback (most recent call last):
  File "[...]/oelint_adv/__main__.py", line 173, in run
    issues += r.check(f, stash)
  File "[...]/oelint_adv/rule_base/rule_var_multilineindent.py", line 29, in check
    _likeliest_indent, _indent_map = self.__line_stats(i.VarValueStripped)
  File "[...]/oelint_adv/rule_base/rule_var_multilineindent.py", line 20, in __line_stats
    return (max(_distribution, key=lambda x: _distribution[x]), list(_map.values()))
ValueError: max() arg is an empty sequence

OOPS - That shouldn't happen - ['crash_repro.bb']
```

#### Reproduction

```bash
oelint-adv --quiet crash_repro.bb
```

###### crash_repro.bb

```bash
RDEPENDS_${PN} = "\
"
```

#### System
- Python 3.9
- oelint-adv master / 2.5.3 / 2.5.2

**Comment by offa** [comment]
Thanks for the fast fix! 🎉
